CREATE TABLE Alunos (
	id_alunos INT NOT NULL AUTO_INCREMENT,
		CONSTRAINT pk_aluno PRIMARY KEY (id_alunos)
  );
  
  CREATE TABLE Cursos(
	id_cursos INT NOT NULL AUTO_INCREMENT,
		CONSTRAINT pk_curso PRIMARY KEY (id_cursos)
  );
  
  CREATE TABLE Notas(
	ID_NOTAS INT NOT NULL AUTO_INCREMENT,
		CONSTRAINT PK_NOTAS PRIMARY KEY (ID_NOTAS)
  );
